application:
  title: "Initializr"
  version: @blossom.version@

initializr:
  default-packaging-mode: JAR

  versions:
  - blossom: 1.1.1
    springboot: 2.0.6.RELEASE
    kotlin: 1.2.71
    maven-war-plugin: 3.2.2
  - blossom: 1.2.0-SNAPSHOT
    springboot: 2.0.6.RELEASE
    kotlin: 1.2.71
    maven-war-plugin: 3.2.2

  groups:
  - name: Core
    description: Blossom core functionalities
    dependencies:
    - name: Blossom Core
      id: blossom-starter-basic
      description: Blossom basic starter (no web interface)
      groupId: com.blossom-project
      artifactId: blossom-starter-basic
      default: true
  - name: Interfaces
    description: Blossom interfaces
    dependencies:
    - name: Blossom UI Web
      id: blossom-starter-ui-web
      description: Blossom UI Web starter (Back-office)
      groupId: com.blossom-project
      artifactId: blossom-starter-ui-web
    - name: Blossom UI Api
      id: blossom-starter-ui-api
      description: Blossom UI Api starter (Back-office)
      groupId: com.blossom-project
      artifactId: blossom-starter-ui-api
  - name: Utilities
    description: Blossom modules to add some utility features to Blossom
    dependencies:
    - name: Business Process Manager
      id: blossom-starter-filemanager
      description: Add a Business Process Manager to Blossom (Camunda)
      groupId: com.blossom-project
      artifactId: blossom-starter-bpmn
  - name: Functionnalities
    description: Blossom modules to add some functionnality to your app'
    dependencies:
    - name: File Manager
      id: blossom-starter-filemanager
      description: File storing and serving feature and tools
      groupId: com.blossom-project
      artifactId: blossom-starter-filemanager
    - name: Articles
      id: blossom-starter-articles
      description: Richtext articles and front serving
      groupId: com.blossom-project
      artifactId: blossom-starter-articles

  initializr-files:
  - original-path: "classpath:/initializr/templates/db/changelog/db.changelog-master.yaml"
    target-path: "src/main/resources/db/changelog/db.changelog-master.yaml"
  - original-path: "classpath:/initializr/templates/application.yml.ftl"
    target-path: "src/main/resources/application.yml"
  - original-path: "classpath:/initializr/templates/messages.properties"
    target-path: "src/main/resources/messages.properties"
